### ISSUE TITLE
Sort should allow for an empty sequence and return an empty sequence

### ISSUE THREAD

**Issue by lcahlander** [eXist-db/semver.xq#10]
**Is your feature request related to a problem? Please describe.**
Sometimes I end up calling the sort with an empty sequence.  I do not want to haveto test if the list is empty before calling this function.

**Describe the solution you'd like**
Allow for an empty sequence of version strings and return an empty sequence when received.

**Describe alternatives you've considered**
I can write my own function to test and then call the sort, but I think that it would be better if the sort handled an empty sequence.

**Comment by joewiz** [comment]
The semver.xq library is strict by default, but a lax mode is available for many functions if you pass a `$coerce` parameter of `true()` - which causes the function to try its best to interpret an input as a valid semver string rather than throwing an error. For example:

```
xquery version "3.1";

import module namespace semver = "http://exist-db.org/xquery/semver";

semver:sort(("1.2.3", "0.1.2", ""), true())
```

returns:

```
"0.0.0"
"0.1.2"
"1.2.3"
```

Also, there is a `semver:validate()` function that lets you test strings before passing them to functions in their default, string mode.

**Comment by joewiz** [comment]
I think my answer addresses your issue, so I'll close it. But feel free to reopen it if you feel it doesn't.
